-   id: clang-format-diff
    name: clang-format
    description: ''
    entry: sh -c 'git diff -U0 --no-color --relative HEAD^ | clang-format-diff.py -p1 -i'
    language: python
    'types_or': [c++, c, c#, cuda, java, javascript, json, objective-c, proto, textproto, metal]
    args: ["-style=file"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '2.9.2'
